apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: maven-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maven-webapp
  template:
    metadata:
      labels:
        app: maven-webapp
    spec:
      containers:
      - name: my-cont
        image: arunhub2/maven-web-app:latest
        ports:
        - containerPort: 80
  ----------------
apiVersion: v1
kind: Service
metadata:
  name: maven-webapp-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 80  # Port on the pods
    #nodePort: 30000   # Port accessible externally on each node
  selector:
    app: maven-webapp  # Select pods with this label
