apiVersion: v1
kind: Service
metadata:
  name: maven-webapp-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 80  # Port on the pods
    #nodePort: 30000   # Port accessible externally on each node
  selector:
    app: maven-webapp  # Select pods with this label
