name: github actions demo
on: push
jobs:
  demo_job:
    runs-on: self-hosted
    steps:
      - name: hello world job
        run: echo "hello world, hi from github!"
      - name: git repo clone
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
      - name: Set up Maven
        run: |
            echo ${GITHUB_WORKSPACE}
            cd ${GITHUB_WORKSPACE}
            sh ./maven_install.sh
      - name: Build with Maven
        run: mvn clean package
