name: github actions demo
on: push
jobs:
  demo_job:
    runs-on: self-hosted
    steps:
      - name: hello world job
        run: echo "hello world, hi from github!"
      - name: git repo clone
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
      - name: Set up Maven
        uses: actions/setup-maven@v1
        with:
           maven-version: '3.9.8' # Specify the Maven version you need
      - name: Build with Maven
        run: mvn clean package
